module.exports = {
    quotes: [
        "Jakby tak Mickiewiecz pisał to by go nawet z Azerbejdżanie czcili ~ Szymon Pońc 2019",
        "Jesteś kurwa mnichem, jesteś kurwa człowiekiem na ubodze ~Sylwester Hodura 2019",
        "Nie ma, kurwa , nie ma kurwa dzisiaj takiej piosenki co by mnie wykurwiła z kapci - Szymon Kamiński 2019",
        "Chuj kurwa anna grodzka nie ugram tego - Szymon Pońc 2019",
        "Przestań eqzystować - Sylwester Hodura 2019",
        "Jak jest pobyt to jest podaż - Sylwester Hodura 2019",
        "Jaki gruby taki jeździ - Franciszek Plisz 2019",
        "-Kiedy masz urodziny?  -W sierpniu.	-Ile?",
        "Zawsze jest jakiś pajac którego trzeba zabić ...  to jest smutna prawda - Sylwester Hodura 2019",
        "Jestem kurwa myślicielem możesz mi mówić wujek myśliciel - Szymon Kamiński 2019",
        "Nie bądź gruby - Baweł Pujok 2019",
        "Na niego to polegać jak na jakimś gównie - Mosze zimmerman o CHŁOPAKU Z WADOWIC",
        "Nie umiesz czerpać zabawy z dobrej zabawy - Szymon Pońc",
        "Henrich Himmler chuj mnie to obchodzi - Szymoń Pońc",
        "Wawrzeczko musiał dużo tych szczepionek wpierdalać tak z 4 dziennie - Sylwester Hodura o szczepionkach, które powodują homoseksualizm",
        "Kto pierwszy ten pieprzy - Chłopak z Wadowic",
        "Błotna kąpiel w stolcu - Szymon Kamiński",
        "'Kto nie liże pięty jest pierdolnięty' jak tak powiedziałem wczoraj to mieli miny nietęgie - M.Zimmerman",
        "Życie jest proste - Franek Plisz 19.05.2019",
        "Zbyt zachłanny - Franek Plisz 19.05.2019 2:35",
        "'Danny devito powinien grać boga' - Sylwester Honduras	  -Morgana freemana? -Gepard z Pogwizdowa",
        "Twoja stara gryzie meble - Sylwester z honduraa",
        "Jak byś chciał to byś nas wszystkich mógł wyruchać - Zuzanna G do Szymona",
        "Chójbyt to taki odbyt z chujem w środku - Chłopak z Wadowic",
        "Zużywanie prądu powoduje wytwarzanie prądu - Szymon Pońć",
        "Jakbyście byli modliszką, to bylibyście najbardziej spedaloną modliszką na łące? - Geparrdo z dupska",
        "Kac kupka to jest takie ,pokusze się o stwierdzenie ,musujące gówno - Szymon Kamiński",
        "Flagi powinny byc zakazane - Sylwester hodura 2k19",
        "Jak się szybko sra to się nie nudzi. - Franciszek Plisz",
        "Social media dały mi smutki uzależnienia i gówno. - Szymon Kamiński",
        "To będzie nieporównywalny smród jakby jakiś behemot się zesrał. - Franciszek Plisz",
        "Za okradanie skąpych ludzi powinna być kara śmierci - Franek",
        "Weźcie po 3 lub 4 zł w błonie żeby każdym miał ogromną prośbą bo będzie ciężko z wydawaniem - Bartemiusz Mors 2019",
        "Może tego nie robi podświadomie, może to robi podświadomie - Szymon Pońc 23.06.2019",
        "Chcesz wrócić do domu w całym czy w jednym kawałku? - Dawid Amor Cieślar",
        "Smajdor by już kciuki lizal - Gepard z Pogwizdowa.",
        "dwa na jeden jest chujowe, lepsze jest dwa na jeden - Szymon Kamiński najebany na piątym piętrze hotelu w Wilnie.",
        "ale ten wiatr jest dobry, czuję się jak Zeus idąc przez ten wiatr Szymon K.",
        "One minut bylo ten minut temu... later... ago - Sylwester z Hondurasu",
        "Ja ci pokażę jak się gwałci - Najebany i  napalony Kolara",
        "To moja wina, to ja wyciągnąlem szachownicę i poustawiałem na niej pionki - Słynny żydowski poeta w nocy",
        "Ale jest wysoka wysoka temperatura, mam nadzieję, że wystąpi ten opad - Simon Kavinsky",
        "dziewczyny nie mają ładnych tekstur - Kamil Krzywoń 2k19",
        "Kurwa co ja znalazłem, jakaś podwodna woda - Michał 2k19",
        "Kamil ma łeb jak sklep - duży i pusty - Gepard z Pogwizdowa",
        "Zawsze się trochę gwałci - Kolara",
        "Aniele boży stróżu mój chałwa ci - Plisz",
        "Seks to jest przekładanie części ciała przez inne części ciała w stosunku przeciwnym - Jakub smajdor o 3 rano po hektolitrach alkoholu",
        "Obserwuję wielki kamień - Krawczyk",
        "Człowiek dostosuj się - Szymon P. 2019",
        " skurwyński zwyczaj informatyków - Szymoń Ponc",
        "więcej cie matka nie miała - Kamiński Szymon",
        "to był rzut losu  - Mosze Zimermman",
        "Babranie się w gównie za pomocą szczotki do butów - Szymon 'Andrzej strzelam' Kamiński",
        "On cie poskłada jak oregano - Szymon P.",
        "Moim mrazeniem jest posiadanie rodziny, mrazeniem Franka jest posiadanie firmy i majątku, nie wiem jakie jest twoje wrażenie Michał, nie wiem jakie jest twoje wrażenie Antek, ale moim zdarzeniem jest posiadanie własnej rodziny - Szymon 'Ifrit' Kamiński",
        "Dryfuje wokół fal - Sylwester Hodura na pytanie co robicie jak macie chcice",
        "-Paweł który to już szlug? -Druga paczka. -A dla czego taki skrzywiony? -Bo jest smaczny",
        "Zagłębiaj się w te nuty, czuj ten galaktyczny lot - Franek",
        "-Kiedy tu się zrobiło ciemno? Słońce zachodzi koło 19. -Jesteś nieoceniony Paweł",
        "-Twój stary pijanszy tańczy na planszy - st00pkarz Kamiński o Michale Wadowskim",
        "Ustawienia wszechświata mi się nie zgrały - Plisz po zrobieniu czegoś dziwnego",
        "Ja przyjdę do domu i będę żarł ser, mam ochotę na ser - Franek",
        "- Krzysiu Kolarczyk to ty rozmawiasz? - No cóż ~ sytuacja na polskim",
        "Jak to zaśpiewamy to nas z karaoke wypierdolą - Szymon K.o 'Mine Diamonds'",
        "Czy wam też tak jaja jebią? - Krzywonius",
        "czy jak sie ruchasz to cie to nie możesz zjeść batona? - POŃC",
        "Gówno wracające jak bumerang - Szymon Kamiński",
        "Stolec Perlage - Szymon Kamiński v2",
        "Gówno szampańskie - wysrywasz zwykłe gówno (jak korek) i potem masz srakę - Szymon Kamiński v3",
        "Zawsze możesz powiedzieć, że masz antidotum w ryju i wtedy się z kolejną przeliższesz - Sylwester Hodura o tzw. 'Kuchejdzie'",
        "Jutro wiara musi wygrać z nauką - Franciszek o sprawdzianie z fizyki",
        "Jestem w sytuacji podbramkowej Michał, umieram na... pierdoloną rzeżączkę - Sylwester również o sprawdzianie z fizyki",
        "słabnia z 17 - Szymon K",
        "Stara Michała tańczyła w Must Be the Music. - Kogo (tańczyła)? - Kamil",
        "Ale jestem śliczny - Franek widząc swoje zdjęcie",
        "Ale pyszny Wachauer - Smajdor",
        "Oranie krzemiennym lemieszem - Jakiś typ o sapiosexualności",
        "Chuj mnie zalewa - Patryk nasz mistrz",
        "Ja się ślizgam jak bobsleje, przede mną jest dwóch gości i szorują podłogę - Pońcek",
        "Kiedyś tam musi być orgia - Dawid o domu Maćka wymachując rękami",
        "Temperatura ok. -5 stopni 	-Idź do środka, bo tu jest zimno 	- Dziewczyna Krystiana Franka	-Przecież tu jest 40 stopni! - ożarty Plisz",
        "Jutro wstaję o 3:90 - Pońcek",
        "Ten mod działa cały czas, nie jest jak wiagra - Marcin Kołowrot Karwot",
        "Zasada zachowania masy w związku została zachowana, ona schudnęła on zgrubł - Patryk o Bobiku i Blasze",
        "Wawrzeczko jest oślizgły. Ja sie go boję - Maciej Moczała",
        "-To jest jak mieszanie złota z gównem. 	-Porównujesz Maćka do gówna?	-Nie , ja porównuje go do rasowego bękarta - Paweł Bujok o związku Szprychy z Maćkiem",
        "Zważ mnie teraz szmato! - Pavel",
        "Jeździła by sobie Wunderbaumem po piździe - Szymon K",
        "Jest rok 2001 po Chrystusie jest rok 2002 po Chrystusie - Bujok przyjebany bez snu",
        "Widziałem strach w moich oczach - Zimmerman przed atakiem Smajdora",
        "Kupię sobie planetoidę - Plisz apropos swego egocentryzmu",
        "Czuję się dzisiaj jako jakiś mącichuj - M.Zimmerman",
        "Po ryju wygląda na wyższą - Szymon K o doopie Maćka",
        "-Franek down under.  –Nie, bo leżę dołem - Wadowski z Zimmermanem",
        "Permanętnie głupi! Nie odwołuję tych słów - M.Zimmerman o bocianie po roku",
        "Tej kobiecie się należy bomba w samochodzie - Mosze Zimmerman o Memes",
        "Krew jest biżuterią wojowników - Smajdor 28.03.2k19.Godzina  8.17",
        "Dariusz Obszar to kutapsztal ~ Szymonk o skurwielu",
        "Kiedy nie możesz zmienić przebiegu zmieñ licznik - Jakub smajdor o liczeniu słöw",
        "Ja chce być jak Smajdor, chce być fajny, chce nie spać - Paweł B.o sobie",
        "Nasza wirtualka zostala zgwałcona w fazie płodowej - Najbardziej przeciętny człowiek na świecie",
        "Przy takich dziewczynach jak ona dobre chłopaki  patrzą na świat z zaświatów - Szymonk o Wiktorii Pilak",
        "Dwanascie prac Vivaldiego - Szymonk o dobrej muzyce",
        "Ty jestes takim umiarkowanym skurwysynem - Smajdor o M.Zimmermanie",
        "Albo cytujesz albo gejujesz - Szymonk o Szymonk",
        "Ryj płaski jak sandał mojżesza - M.Zimmerman o Juanie De Loresie",
        "Jeżeli obiekt porusza się względem obserwatora jest on rzeką. My jesteśmy rzeką - SzymonK o rzeczy",
        "-Bartolo Mors   -Kurwa kto!?   -Bartolo Mors   - Masz na myśli Walarusa?   -No ale on wygląda jak Bartolo Mors.” ~Mosze Zimmerman",
        "Czy jakbyś był modliszką to byś był najbardziej spedaloną modliszką na łące? - M.Zimmermanem",
        "that's i like it - Baweł Pujok",
        "Kolega to chyba z Al-Kaidy, bo ma dobre ładunki - random z CSa o nicku Zdunek",
        "Jak mówisz Sylwek nazwę choroby to nie mówisz ratak tylko katar - Franek o schizofre(m)ii",
        "Dupczysz albo pupczysz. Nie pytaj co właśnie powiedziałem bo szczerze ci powiem że nie wiem - Franz",
        "'Cing, Ciang, Ciung, ja lubić ryż, bo ja mieć małe oczka' - Franek Plisz, śpiewając 'Mam Te Moc' po Mandaryńsku.",
        "Co to do kurwy jest Babu Frik, gdzie się tak mówi? - jakiś Kędzior czytając jak nazywany jest Mikołaj w różnych częściach Polski",
        "patrz na jego staty to nie jest zwykły człowiek z łapanki - KOŁOWROT",
        "MajonezLower, wykolejeniec, pojeb... jakby jeszcze z celownikiem stał, no pojeb Franek Plisz.",
        "Rozgrzany jak mieć, muszę jak piec - Norman o 5:01 nad ranem po 9 godzinach karaoke",
        "Albo wiesz co Boston, wypierdalaj z tej sceny - Norman koło 3",
        "Musze zapierdalać jak mały szerszeń - Franek",
        "Strasznie pierdolisz - Tatiana do Szymona o 00:46",
        "Ręka Kamińskiego, jego jaja i muzyka ambient - tego mi brakuje w nowym roku - Franek Plisz 6:28",
        "Nie jestem gejem, ale muszę przyznać, że był wspaniałym mężczyzną - Barefoot Pookie",
        "Michał Wadowski to jest on, nie jest - Plish",
        "ja, doktor dre i kurwa road - Najebany Pońcek o 01:23",
        "ja przestaje, kurwa czucie w nogach - Szymon Pońc 01:57",
        "jestem czarnuchem i xcuzje moc z westcoastu, gangsta stilll dre, bo ja wiem że los anglexse nie pdoa sie - Franek na ogólnym o 01: 29",
        "najbardziej bolą jagody - Franek po shajcowaniu się bazy.",
        "Patryk jesteś jeszcze z nami? Nie poddawaj się, nie idź spać jeszcze... dostaniesz medal jak wytrwasz... jeszcze chwila... już to mamy - Franek i Marcin podczas oblężenia Hiszpani.",
        "Legionista małego fiuta - Jakiś typ",
        "Szmaty i kufel - Michał",
        "na ciebie liczyć to jak konie kraść - Wadowić",
        "Oceny z matmy ze 2 piątki z nich są z czego innego - Bercik 2020",
        "Jeśli ktoś wie czego grygierek będzie pytać jutro to napisz cze bo nwm czy Przybosia czy awangardy? - Bert po klefedronie",
        "Zauważyłem, że ja rzadko mówię swoje imię... rzadko się mówi swoje imię - Dzemor Plisz.",
        "już za późno na tą godzinę - Michał Wadowki",
    ]
}

